### ISSUE TITLE
Insert / Retrieve seems to be wrong

### ISSUE THREAD

**Issue by MarkusMiller** [timohausmann/quadtree-js#1]
I tried to use this quadtree to organise a set of tiles in the range from (0 / 0) to (4000 / 4000). There were 16 tiles in total, each 1000 wide and 1000 high. Each sub division of the tree should hold only one tile, so i specified a maximum of 1 element per division. After I inserted all my tiles the quad tree generated 4 sub divisions with 4 elements in each sub division (?). Ok, in doubt, I can live with that but then I tried to retrieve all elements in the given region: x 0 y 0 w 1000 h 1000. That is the upper left sector. I'd expected a result of up to 4 tiles. The function returned 13 of 16 tiles. If you number my 16 tiles (4 x 4 rows and cols) from 0 to 15 (0 upper left, 3 upper right) I'd expected the tiles 0, 1, 4 and 5. In fact I got 0, 1, 2, 4, 5, 6, 8, 9, 10, 11, 12, 13. The same strange behaviour occures in your example. But there I thought it might have something to do with javascript runtime and the movement in the scene. The quadtree seems broken to me. Maybe you could have a look on it...

**Comment by timohausmann** [comment]
Hey, again sorry for the late response, didn't see the issues here. 
This may be intended use and a misunderstanding. Some example code would be awesome.

What I understood you tried to achieve something like this? http://jsfiddle.net/ua9203zb/2/
It has a 4000x4000 area with 4x4 possible quadtrees, limited by the max_levels of 2. 
The top left 1000x1000 is constantly retrieved and those objects are highlighted in white.
(Draw functions are scaled down by 10)

**Comment by MarkusMiller** [comment]
Yes, your setup is right and this screenshot shows, what I find unexpected with it:
http://s27.postimg.org/63s8wzt4z/Quadtree.png

But if I remember right, it just occures with non-point Items. It is totally fine, when you just use point-dimensional items

I modified your example a bit: http://jsfiddle.net/zwcckn5s/ 
All retrieved tiles are drawn in blue when you query for the upper left corner (0, 0, 1000, 1000)

**Comment by timohausmann** [comment]
I did some updates on the code and came across this post one again. 
Like I said in the other issue months ago, the screenshot shows intended behaviour since the Quadtree only narrows down the objects of possible collision.

The problem in your example is the dimensions of the objects, they are 1000x1000 units, aligned in a grid. Same grid as the Quadtree, I don't see the actual point in this? They cannot fit into one exact subnode, since they are same size. This is where the screenshot effect comes in: all objects touching a shared border with the retrieve area are possible candidates.

When you debug myTree in the given example, you see that all objects belong to the master node, the Quadtree itself. 

I reduced the objects dimensions by 2 units, this way it works http://jsfiddle.net/zwcckn5s/1/
When you debug there, objects are stored in subnodes, the way it should be.

There are new examples and docs, maybe check them out.
