### ISSUE TITLE
Infinite loop issue

### ISSUE THREAD

**Issue by abacaj** [timohausmann/quadtree-js#4]
I've tried using this library - seems like it ends up in an infinite loop here:

```
            while( i < this.objects.length ) {

                index = this.getIndex( this.objects[ i ] );

                if( index !== -1 ) {                    
                    this.nodes[index].insert( this.objects.splice(i, 1)[0] );
                } else {
                    i = i + 1;
                }
            }
```

**Comment by timohausmann** [comment]
Hi, this part of the code is responsible for inserting objects in sub-nodes when the current node is full and splits. You can see it working in the examples.

If you can provide a full example of your code at [jsbin](http://jsbin.com/?html,css,js,output) or similar, I will have a look at the problem.

**Comment by abacaj** [comment]
Seems It was an error in my code (most likely) - but why does my code return all the objects when I try to retrieve one (even though they are clearly not in the same x,y coordinate)

Heres the jsbin: http://jsbin.com/qabigu/8/edit?js,console,output

```
var collidableItems = qt.retrieve(objects[4]);
console.log(collidableItems.length);   
```

The above logs 5 items even though I have moved their x, y coordinates.

**Comment by timohausmann** [comment]
I can see how that may seem confusing while testing around. I often find it useful to visualize things: http://jsbin.com/ququdobicu/1/edit?js,output Try chaning the 2nd argument (max_objects) in the first line "10" to "1" and you will see it working.

[The problem here is that the _default_ max_objects is set to 10. With only 5 objects inserted, the Quadree never splits.](https://github.com/timohausmann/quadtree-js/blob/master/README.md) You always get all objects from the node that was detected in your retrieve(), and since you only have one node, you get all the objects.

Also note that the retrieving isn't very border sensitive: you are retrieving for {x: 500, y: 500, width: 100, height: 100}, which lays in the total center, on the borders of the subnodes, therefore not fitting fully into one subnode. 

I guess Quadtrees really first shine when have a lot of objects ;-)

**Comment by abacaj** [comment]
Very nice thanks for the walkthrough. I suppose I needed to refresh on quadtress and also overlooked the default options (10) objects. 

From my understanding that means the root (grid) node never split into smaller nodes because there was only 5 items, and since the root node is the whole grid it returned all items in that bounding box. That's why it makes sense when there isn't alot of items to set a lower threshold so that the root node can split sooner and return the closest objects in the sub nodes.

Again thank you, great library I'm actually surprised how other full blown grid libraries don't make use of this data structure. I'm referring to this library in particular - http://hootsuite.github.io/grid/

**Comment by timohausmann** [comment]
Yay, exactly! You are welcome ;-)
